import type {
  Collection,
  Exhibition,
  Employee,
  FinanceRecord,
  ConservationRecord,
  ResearchProject,
  SecurityLog,
  ProcurementItem,
} from "./types"

export const collections: Collection[] = [
  {
    id: "COL001",
    name: "Keris Pusaka Majapahit",
    category: "Senjata Tradisional",
    origin: "Jawa Timur",
    year: "Abad ke-14",
    condition: "Baik",
    location: "Galeri Utama - A1",
    acquisitionDate: "1985-03-15",
    value: 500000000,
    description: "Keris bersejarah dari era Kerajaan Majapahit dengan pamor khas.",
  },
  {
    id: "COL002",
    name: "Topeng Barong Bali",
    category: "Seni Pertunjukan",
    origin: "Bali",
    year: "Abad ke-19",
    condition: "Perlu Perawatan",
    location: "Galeri Timur - B3",
    acquisitionDate: "1992-07-20",
    value: 150000000,
    description: "Topeng Barong untuk upacara keagamaan Hindu Bali.",
  },
  {
    id: "COL003",
    name: "Naskah Kuno Sunda",
    category: "Manuskrip",
    origin: "Jawa Barat",
    year: "Abad ke-16",
    condition: "Dalam Restorasi",
    location: "Ruang Konservasi",
    acquisitionDate: "2001-11-10",
    value: 750000000,
    description: "Naskah lontar berisi catatan sejarah Kerajaan Sunda.",
  },
  {
    id: "COL004",
    name: "Patung Buddha Sriwijaya",
    category: "Arkeologi",
    origin: "Sumatera Selatan",
    year: "Abad ke-8",
    condition: "Baik",
    location: "Galeri Utama - A3",
    acquisitionDate: "1978-05-25",
    value: 1200000000,
    description: "Patung Buddha perunggu dari era Kerajaan Sriwijaya.",
  },
  {
    id: "COL005",
    name: "Batik Tulis Kraton Jogja",
    category: "Tekstil",
    origin: "Yogyakarta",
    year: "Abad ke-20",
    condition: "Baik",
    location: "Galeri Barat - C2",
    acquisitionDate: "2010-08-17",
    value: 85000000,
    description: "Kain batik tulis dengan motif parang rusak barong.",
  },
  {
    id: "COL006",
    name: "Gamelan Pelog Slendro",
    category: "Alat Musik",
    origin: "Jawa Tengah",
    year: "Abad ke-18",
    condition: "Baik",
    location: "Galeri Selatan - D1",
    acquisitionDate: "1995-12-01",
    value: 350000000,
    description: "Set gamelan lengkap dari Keraton Surakarta.",
  },
]

export const exhibitions: Exhibition[] = [
  {
    id: "EXH001",
    name: "Warisan Nusantara",
    startDate: "2024-01-15",
    endDate: "2024-06-30",
    status: "Ongoing",
    location: "Galeri Utama",
    curator: "Dr. Siti Rahayu",
    collections: ["COL001", "COL004", "COL006"],
    visitors: 15420,
  },
  {
    id: "EXH002",
    name: "Seni Tekstil Indonesia",
    startDate: "2024-07-01",
    endDate: "2024-12-31",
    status: "Upcoming",
    location: "Galeri Barat",
    curator: "Prof. Ahmad Wijaya",
    collections: ["COL005"],
    visitors: 0,
  },
  {
    id: "EXH003",
    name: "Jejak Maritim Sriwijaya",
    startDate: "2023-06-01",
    endDate: "2023-12-15",
    status: "Completed",
    location: "Galeri Timur",
    curator: "Dr. Budi Santoso",
    collections: ["COL004"],
    visitors: 28350,
  },
]

export const employees: Employee[] = [
  {
    id: "EMP001",
    name: "Dr. Siti Rahayu",
    position: "Kepala Kurator",
    department: "Kurasi",
    email: "siti.rahayu@museum.go.id",
    phone: "+62 812-3456-7890",
    joinDate: "2010-03-15",
    status: "Active",
  },
  {
    id: "EMP002",
    name: "Budi Santoso",
    position: "Konservator Senior",
    department: "Konservasi",
    email: "budi.santoso@museum.go.id",
    phone: "+62 813-2345-6789",
    joinDate: "2012-07-20",
    status: "Active",
  },
  {
    id: "EMP003",
    name: "Dewi Anggraini",
    position: "Manager Keuangan",
    department: "Keuangan",
    email: "dewi.anggraini@museum.go.id",
    phone: "+62 814-3456-7890",
    joinDate: "2015-01-10",
    status: "Active",
  },
  {
    id: "EMP004",
    name: "Eko Prasetyo",
    position: "Kepala Keamanan",
    department: "Keamanan",
    email: "eko.prasetyo@museum.go.id",
    phone: "+62 815-4567-8901",
    joinDate: "2011-09-05",
    status: "Active",
  },
  {
    id: "EMP005",
    name: "Rina Wulandari",
    position: "Staff Ticketing",
    department: "Pelayanan",
    email: "rina.wulandari@museum.go.id",
    phone: "+62 816-5678-9012",
    joinDate: "2020-02-01",
    status: "Active",
  },
]

export const financeRecords: FinanceRecord[] = [
  {
    id: "FIN001",
    date: "2024-01-15",
    type: "Income",
    category: "Tiket Masuk",
    amount: 45000000,
    description: "Pendapatan tiket bulan Januari",
    status: "Completed",
  },
  {
    id: "FIN002",
    date: "2024-01-20",
    type: "Expense",
    category: "Konservasi",
    amount: 25000000,
    description: "Biaya restorasi naskah kuno",
    status: "Completed",
  },
  {
    id: "FIN003",
    date: "2024-02-01",
    type: "Income",
    category: "Donasi",
    amount: 100000000,
    description: "Donasi dari Yayasan Budaya Nusantara",
    status: "Completed",
  },
  {
    id: "FIN004",
    date: "2024-02-10",
    type: "Expense",
    category: "Operasional",
    amount: 35000000,
    description: "Biaya listrik dan air",
    status: "Completed",
  },
  {
    id: "FIN005",
    date: "2024-02-15",
    type: "Income",
    category: "Pameran",
    amount: 75000000,
    description: "Sponsor pameran Warisan Nusantara",
    status: "Approved",
  },
]

export const conservationRecords: ConservationRecord[] = [
  {
    id: "CON001",
    collectionId: "COL003",
    collectionName: "Naskah Kuno Sunda",
    type: "Restoration",
    date: "2024-01-10",
    technician: "Budi Santoso",
    status: "In Progress",
    notes: "Proses digitalisasi dan preservasi fisik",
  },
  {
    id: "CON002",
    collectionId: "COL002",
    collectionName: "Topeng Barong Bali",
    type: "Inspection",
    date: "2024-02-01",
    technician: "Maya Kusuma",
    status: "Completed",
    notes: "Diperlukan pembersihan dan pengawetan",
  },
  {
    id: "CON003",
    collectionId: "COL001",
    collectionName: "Keris Pusaka Majapahit",
    type: "Treatment",
    date: "2024-02-15",
    technician: "Budi Santoso",
    status: "Scheduled",
    notes: "Pemolesan dan anti-karat berkala",
  },
]

export const researchProjects: ResearchProject[] = [
  {
    id: "RES001",
    title: "Studi Komparatif Keris Nusantara",
    researcher: "Dr. Hendra Wijaya",
    startDate: "2023-06-01",
    status: "Active",
    collections: ["COL001"],
    publications: 2,
  },
  {
    id: "RES002",
    title: "Dokumentasi Digital Naskah Kuno",
    researcher: "Prof. Ani Suryani",
    startDate: "2024-01-15",
    status: "Active",
    collections: ["COL003"],
    publications: 0,
  },
  {
    id: "RES003",
    title: "Sejarah Maritim Sriwijaya",
    researcher: "Dr. Budi Santoso",
    startDate: "2022-03-01",
    endDate: "2023-12-31",
    status: "Completed",
    collections: ["COL004"],
    publications: 5,
  },
]

export const securityLogs: SecurityLog[] = [
  {
    id: "SEC001",
    timestamp: "2024-02-15T08:30:00",
    type: "Access",
    location: "Pintu Utama",
    description: "Pembukaan museum - shift pagi",
    severity: "Low",
  },
  {
    id: "SEC002",
    timestamp: "2024-02-15T10:15:00",
    type: "Alert",
    location: "Galeri Utama - A1",
    description: "Sensor gerak terdeteksi aktivitas tidak biasa",
    severity: "Medium",
  },
  {
    id: "SEC003",
    timestamp: "2024-02-15T14:00:00",
    type: "Audit",
    location: "Ruang Server",
    description: "Pemeriksaan rutin sistem CCTV",
    severity: "Low",
  },
  {
    id: "SEC004",
    timestamp: "2024-02-14T22:30:00",
    type: "Incident",
    location: "Galeri Barat",
    description: "Pengunjung menyentuh display",
    severity: "Medium",
  },
]

export const procurementItems: ProcurementItem[] = [
  {
    id: "PRO001",
    name: "Vitrin Display Kaca",
    vendor: "PT. Kaca Indah",
    quantity: 5,
    unitPrice: 15000000,
    totalPrice: 75000000,
    status: "Approved",
    requestDate: "2024-01-20",
    expectedDate: "2024-03-15",
  },
  {
    id: "PRO002",
    name: "AC Central Galeri",
    vendor: "CV. Sejuk Abadi",
    quantity: 2,
    unitPrice: 45000000,
    totalPrice: 90000000,
    status: "Ordered",
    requestDate: "2024-01-25",
    expectedDate: "2024-02-28",
  },
  {
    id: "PRO003",
    name: "Label Koleksi Digital",
    vendor: "PT. Digital Museum",
    quantity: 100,
    unitPrice: 500000,
    totalPrice: 50000000,
    status: "Requested",
    requestDate: "2024-02-10",
  },
]

export const dashboardStats = {
  totalCollections: 1250,
  activeExhibitions: 3,
  monthlyVisitors: 15420,
  totalRevenue: 285000000,
  collectionsGrowth: 5.2,
  visitorsGrowth: 12.3,
  revenueGrowth: 8.7,
  exhibitionsGrowth: 0,
}

export const visitorStats = [
  { month: "Jan", visitors: 12500, revenue: 45000000 },
  { month: "Feb", visitors: 14200, revenue: 52000000 },
  { month: "Mar", visitors: 15800, revenue: 58000000 },
  { month: "Apr", visitors: 13400, revenue: 48000000 },
  { month: "Mei", visitors: 16200, revenue: 62000000 },
  { month: "Jun", visitors: 15420, revenue: 55000000 },
]

export const collectionCategories = [
  { name: "Senjata Tradisional", count: 245, percentage: 19.6 },
  { name: "Tekstil", count: 312, percentage: 24.9 },
  { name: "Arkeologi", count: 198, percentage: 15.8 },
  { name: "Manuskrip", count: 156, percentage: 12.5 },
  { name: "Seni Pertunjukan", count: 189, percentage: 15.1 },
  { name: "Alat Musik", count: 150, percentage: 12.0 },
]
